"""job source integration: provider query cache

Revision ID: 195c3913ae34
Revises: b9fde5aa2276
Create Date: 2026-08-14 18:49:24.787647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195c3913ae34'
down_revision = 'b9fde5aa2276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_query_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('query_key', sa.String(length=300), nullable=False),
    sa.Column('last_queried_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'query_key', name='uq_provider_query_cache_source_query')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_query_cache')
    # ### end Alembic commands ###
