"""Phase 3: job matches and AI usage tracking

Revision ID: 272f76cda025
Revises: 38867e437418
Create Date: 2026-08-11 00:40:47.132122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272f76cda025'
down_revision = '38867e437418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_user_id'), ['user_id'], unique=False)

    op.create_table('job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.String(length=30), nullable=False),
    sa.Column('skipped_categories', sa.JSON(), nullable=False),
    sa.Column('profile_updated_at_snapshot', sa.DateTime(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('narrative_text', sa.Text(), nullable=True),
    sa.Column('narrative_provider', sa.String(length=30), nullable=True),
    sa.Column('narrative_generated_at', sa.DateTime(), nullable=True),
    sa.Column('improvement_tips_text', sa.Text(), nullable=True),
    sa.Column('improvement_tips_provider', sa.String(length=30), nullable=True),
    sa.Column('improvement_tips_generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_job_match_user_job')
    )
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_matches_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_matches_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_matches_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_matches_job_id'))

    op.drop_table('job_matches')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_user_id'))

    op.drop_table('ai_usage')
    # ### end Alembic commands ###
