"""Add dashboard_insights table

Revision ID: 4bbab0dec59b
Revises: 5b4fe35a6528
Create Date: 2026-08-27 21:09:59.307815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bbab0dec59b'
down_revision = '5b4fe35a6528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('reliability', sa.String(length=20), nullable=True),
    sa.Column('profile_updated_at_snapshot', sa.DateTime(), nullable=True),
    sa.Column('application_count_snapshot', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_insights_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_insights_user_id'))

    op.drop_table('dashboard_insights')
    # ### end Alembic commands ###
