"""Add reliability and edit tracking fields for AI-backed models

Revision ID: 5b4fe35a6528
Revises: 5405dd108168
Create Date: 2026-08-26 04:53:26.001612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4fe35a6528'
down_revision = '5405dd108168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reliability', sa.String(length=20), nullable=True))

    with op.batch_alter_table('cv_profile_statements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reliability', sa.String(length=20), nullable=True))

    with op.batch_alter_table('generated_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reliability', sa.String(length=20), nullable=True))

    with op.batch_alter_table('gmail_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_suggestion_reliability', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reply_suggestion_edited_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('interview_preps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('narrative_reliability', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('improvement_tips_reliability', sa.String(length=20), nullable=True))

    with op.batch_alter_table('profile_coachings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reliability', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_coachings', schema=None) as batch_op:
        batch_op.drop_column('reliability')

    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.drop_column('improvement_tips_reliability')
        batch_op.drop_column('narrative_reliability')

    with op.batch_alter_table('interview_preps', schema=None) as batch_op:
        batch_op.drop_column('edited_at')

    with op.batch_alter_table('gmail_messages', schema=None) as batch_op:
        batch_op.drop_column('reply_suggestion_edited_at')
        batch_op.drop_column('reply_suggestion_reliability')

    with op.batch_alter_table('generated_emails', schema=None) as batch_op:
        batch_op.drop_column('reliability')

    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.drop_column('reliability')

    with op.batch_alter_table('cv_profile_statements', schema=None) as batch_op:
        batch_op.drop_column('edited_at')

    with op.batch_alter_table('company_insights', schema=None) as batch_op:
        batch_op.drop_column('reliability')

    # ### end Alembic commands ###
