"""jooble request_count counter for lifetime budget tracking

Revision ID: 7b444a7a9b89
Revises: 9aaadb1f6b0b
Create Date: 2026-08-29 06:00:55.957617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b444a7a9b89'
down_revision = '9aaadb1f6b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_source_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_source_settings', schema=None) as batch_op:
        batch_op.drop_column('request_count')

    # ### end Alembic commands ###
