"""Phase 5: Gmail OAuth connections, reply tracking, per-category match scores

Revision ID: 80aff7061f70
Revises: 05df5de82942
Create Date: 2026-08-11 01:40:05.996399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80aff7061f70'
down_revision = '05df5de82942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_email', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.String(length=500), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('gmail_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=100), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=100), nullable=True),
    sa.Column('rfc_message_id', sa.String(length=255), nullable=True),
    sa.Column('from_address', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('classified_intent', sa.String(length=30), nullable=True),
    sa.Column('classification_confidence', sa.String(length=20), nullable=True),
    sa.Column('classification_notes', sa.Text(), nullable=True),
    sa.Column('classification_provider', sa.String(length=30), nullable=True),
    sa.Column('ai_suggested_reply', sa.Text(), nullable=True),
    sa.Column('ai_suggested_reply_provider', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_message_id')
    )
    with op.batch_alter_table('gmail_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gmail_messages_application_id'), ['application_id'], unique=False)

    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_scores', sa.JSON(), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.drop_column('category_scores')

    with op.batch_alter_table('gmail_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gmail_messages_application_id'))

    op.drop_table('gmail_messages')
    op.drop_table('gmail_connections')
    # ### end Alembic commands ###
