"""Phase 6: CompanyInsight, BackgroundTask, Document.ai_suggested_doc_type

Revision ID: 8d194632b91b
Revises: 80aff7061f70
Create Date: 2026-08-12 00:57:33.321379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d194632b91b'
down_revision = '80aff7061f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('result_message', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('company_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('profile_updated_at_snapshot', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_company_insight_user_company')
    )
    with op.batch_alter_table('company_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_insights_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_insights_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_suggested_doc_type', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('ai_suggested_doc_type')

    with op.batch_alter_table('company_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_insights_user_id'))
        batch_op.drop_index(batch_op.f('ix_company_insights_company_id'))

    op.drop_table('company_insights')
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_tasks_user_id'))

    op.drop_table('background_tasks')
    # ### end Alembic commands ###
