"""job requirements extraction retry: attempt count and last-attempted timestamp

Revision ID: 9aaadb1f6b0b
Revises: b00ad196d445
Create Date: 2026-08-29 04:18:51.782169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aaadb1f6b0b'
down_revision = 'b00ad196d445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements_extraction_attempts', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('requirements_extraction_last_attempted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('requirements_extraction_last_attempted_at')
        batch_op.drop_column('requirements_extraction_attempts')

    # ### end Alembic commands ###
