"""i18n pass 3 follow-up: locale tracking for dashboard insight and process QA

Revision ID: b00ad196d445
Revises: d0a13f3299ee
Create Date: 2026-08-29 01:01:15.669961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00ad196d445'
down_revision = 'd0a13f3299ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_locale', sa.String(length=5), nullable=True))

    with op.batch_alter_table('process_qa_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_locale', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_qa_answers', schema=None) as batch_op:
        batch_op.drop_column('generated_locale')

    with op.batch_alter_table('dashboard_insights', schema=None) as batch_op:
        batch_op.drop_column('generated_locale')

    # ### end Alembic commands ###
