"""Manual import batches (bulk paste)

Revision ID: b81fb84e4f01
Revises: 8d194632b91b
Create Date: 2026-08-13 14:33:50.382653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81fb84e4f01'
down_revision = '8d194632b91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manual_import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_import_batches_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_import_batches_user_id'))

    op.drop_table('manual_import_batches')
    # ### end Alembic commands ###
