"""Phase 9: profile coaching, interview prep, follow-up email, job explainer, process QA

Revision ID: b9fde5aa2276
Revises: b81fb84e4f01
Create Date: 2026-08-13 16:05:19.008395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fde5aa2276'
down_revision = 'b81fb84e4f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_qa_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_key', sa.String(length=50), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('profile_updated_at_snapshot', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_key', name='uq_process_qa_user_question')
    )
    with op.batch_alter_table('process_qa_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_qa_answers_user_id'), ['user_id'], unique=False)

    op.create_table('profile_coachings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('profile_updated_at_snapshot', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_coachings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_coachings_user_id'), ['user_id'], unique=True)

    op.create_table('job_explainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('explainer_text', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('profile_updated_at_snapshot', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_job_explainer_user_job')
    )
    with op.batch_alter_table('job_explainers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_explainers_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_explainers_user_id'), ['user_id'], unique=False)

    op.create_table('follow_up_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('interview_preps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('prep_text', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('profile_updated_at_snapshot', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_preps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_preps_application_id'), ['application_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_preps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_preps_application_id'))

    op.drop_table('interview_preps')
    op.drop_table('follow_up_emails')
    with op.batch_alter_table('job_explainers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_explainers_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_explainers_job_id'))

    op.drop_table('job_explainers')
    with op.batch_alter_table('profile_coachings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_coachings_user_id'))

    op.drop_table('profile_coachings')
    with op.batch_alter_table('process_qa_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_qa_answers_user_id'))

    op.drop_table('process_qa_answers')
    # ### end Alembic commands ###
