"""job contact_external_fetch_attempted for external-posting contact fallback

Revision ID: c34ab4e91828
Revises: d284078b5462
Create Date: 2026-09-02 04:21:31.101759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34ab4e91828'
down_revision = 'd284078b5462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_external_fetch_attempted', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('contact_external_fetch_attempted')

    # ### end Alembic commands ###
