"""i18n pass 3: track generated locale for follows-UI-language AI features

Revision ID: d0a13f3299ee
Revises: 4bbab0dec59b
Create Date: 2026-08-29 00:17:47.003754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a13f3299ee'
down_revision = '4bbab0dec59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_locale', sa.String(length=5), nullable=True))

    with op.batch_alter_table('cv_profile_statements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_locale', sa.String(length=5), nullable=True))

    with op.batch_alter_table('interview_preps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_locale', sa.String(length=5), nullable=True))

    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('narrative_locale', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('improvement_tips_locale', sa.String(length=5), nullable=True))

    with op.batch_alter_table('profile_coachings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_locale', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_coachings', schema=None) as batch_op:
        batch_op.drop_column('generated_locale')

    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.drop_column('improvement_tips_locale')
        batch_op.drop_column('narrative_locale')

    with op.batch_alter_table('interview_preps', schema=None) as batch_op:
        batch_op.drop_column('generated_locale')

    with op.batch_alter_table('cv_profile_statements', schema=None) as batch_op:
        batch_op.drop_column('generated_locale')

    with op.batch_alter_table('company_insights', schema=None) as batch_op:
        batch_op.drop_column('generated_locale')

    # ### end Alembic commands ###
