"""add User.marketing_consent for registration opt-in

Revision ID: d284078b5462
Revises: df88254c4f2c
Create Date: 2026-08-31 01:14:49.980929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd284078b5462'
down_revision = 'df88254c4f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketing_consent', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('marketing_consent')

    # ### end Alembic commands ###
