"""Add cv_profile_statements table

Revision ID: f3653f96d36d
Revises: 195c3913ae34
Create Date: 2026-08-19 18:04:57.550671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3653f96d36d'
down_revision = '195c3913ae34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_profile_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('statement_text', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('profile_updated_at_snapshot', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cv_profile_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cv_profile_statements_application_id'), ['application_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv_profile_statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cv_profile_statements_application_id'))

    op.drop_table('cv_profile_statements')
    # ### end Alembic commands ###
