"""plans page: user access_expires_at, invitation code access_duration_months

Revision ID: faa3774fd6ec
Revises: 7b444a7a9b89
Create Date: 2026-08-30 04:09:16.731003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa3774fd6ec'
down_revision = '7b444a7a9b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_duration_months', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('access_expires_at')

    with op.batch_alter_table('invitation_codes', schema=None) as batch_op:
        batch_op.drop_column('access_duration_months')

    # ### end Alembic commands ###
